# Numpy Survey

- [NumPy](http://www.numpy.org/) - fast processing for N-dimensional arrays 

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# plot all graphs inline
%matplotlib inline    

print("Numpy version: {}".format(np.__version__))

Numpy version: 1.16.4


## numpy.ndarray

The `numpy.ndarray` is the fundamental type provided by numpy, it is an optimized array container, which stores homogeneous elements (same type) and can be multi-dimensional.  A `numpy` array acts as a sequence similar to a `list` but is an object with many attributes and member functions, some useful attributes are:

- `dtype`: type of data stored: `int[8|16|32|64]`, `uint[8|16|32|64]`, `float[32|64]`
- `ndim`: number of dimensions, also know as the **rank**
- `shape`: tuple w/ rows, columns, depth
- `size`: total number of elements, regrardless of dimensions (product of `shape` elements)
- `itemsize`: size of a single element in bytes
- `nbytes`: `size*itemsize`
- `T`: transpose of array
- `flat`: iterator for flattened elements of array

**Note**: `numpy` does not always distinguish between N X 1 arrays (column vector) and 1 X N arrays (row vector), and transposes between these two are generally unnecessary in `numpy`.

## Array Creation

There are several ways to create an array, many of which are familiar from MATLAB:

In [3]:
a = np.array([1,2,3,4])   # Create from a Python list, dtype is inferred
b = np.arange(4)          # Create a range of values of length 4, starting at 0   
c = np.arange(4.0)        # Same as b but dtype == float64

# Note dtypes are much more specific than int or float
print(a.dtype, b.dtype, c.dtype)
a

int64 int64 float64


array([1, 2, 3, 4])

There are also a wealth of other possibile ways:

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.ones_like(a)    # same length and dtype as input arrray

array([1, 1, 1, 1])

In [6]:
np.zeros(5)    # also a zeros_like

array([0., 0., 0., 0., 0.])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10,20,3)     # start, stop, step - but unclear exactly how many points you'll get

array([10, 13, 16, 19])

In [9]:
np.linspace(10,20,5)   # start, stop, N

array([10. , 12.5, 15. , 17.5, 20. ])

# Two-dimensional arrays

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.ones((5,3))   # 5 rows 3 columns, Note: argument must be a tuple (this is ALMOST universal)  

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
b = np.random.randn(5,3)   # EXCEPT for randn where argument must not be a tuple
b

array([[ 0.88931026,  0.19768436, -0.41871658],
       [-1.15783353, -1.5504955 ,  0.01227084],
       [ 0.01349353, -0.63165772,  0.4708089 ],
       [ 0.3957322 , -0.45932214, -1.43199024],
       [ 2.36057437, -0.68752536,  1.73476142]])

In [ ]:
# np.random.rand((5,3))   # raises TypeError
# np.ones(5,3)            # raises TypeError

the `ones_like` and `zeros_like` functions also handle multi-dimensional arrays just fine

In [16]:
np.zeros_like(b)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
b[1:3, :]

array([[-1.15783353, -1.5504955 ,  0.01227084],
       [ 0.01349353, -0.63165772,  0.4708089 ]])

## Combining or Stiching Arrays

Using Python out of the box we have the `zip` function which combines lists together but in `numpy` we have a richer syntax as we need to accomplish different things with our arrays, the sematics are "more complicated."

In [20]:
x=np.arange(10)
y=x**2
z=x**3+3*x**2+3*x+1

In [21]:
xyz=np.column_stack((x, y, z))  # treat each tuple member as a new column
xyz

array([[   0,    0,    1],
       [   1,    1,    8],
       [   2,    4,   27],
       [   3,    9,   64],
       [   4,   16,  125],
       [   5,   25,  216],
       [   6,   36,  343],
       [   7,   49,  512],
       [   8,   64,  729],
       [   9,   81, 1000]])

In [22]:
np.row_stack((x,y, z))   

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [   0,    1,    4,    9,   16,   25,   36,   49,   64,   81],
       [   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000]])

In [23]:
np.vstack((x,y,z))  # equivalent to row_stack always

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [   0,    1,    4,    9,   16,   25,   36,   49,   64,   81],
       [   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000]])

In [25]:
np.hstack((x,y,z))  # not equivalent to column_stack, hstack more useful for combining two dimensional arrays

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,    0,
          1,    4,    9,   16,   25,   36,   49,   64,   81,    1,    8,
         27,   64,  125,  216,  343,  512,  729, 1000])

In [26]:
np.vstack?

## Loops are Evil !!

For a small number of elements, loops are fine but when you have a large number of elements, the standard Python methods of looping are not always sufficient. The best practice in these cases is to vectorize the operation using numpy which provides operations that act on data as vectos with "comipled C-like" execution speeds, similar to MATLAB.

In [27]:
data = np.random.randn(100000)

In [28]:
%%timeit 
pos_vals = [x for x in data if x > 0]
num_pos_vals = len(pos_vals)

26.4 ms ± 445 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [29]:
%%timeit 
pos_vals = data[data > 0]
num_pos_vals = len(pos_vals)

660 µs ± 19.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [30]:
%%timeit 
num_pos_vals = np.count_nonzero(data > 0)

34.9 µs ± 1.23 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


**NOTE**: If you are tempted to write a loop to process something, take some time to convince yourself that there is no other way to do it.  Usually, when using `numpy` there is always a better and faster way than writing a `for` loop.

## Indexing

Since arrays act mostly like sequences they can be indexed in similar ways using, single indexes and slices, one dimensional arrays are entirely analogous to a Python `list` but 2D arrays are more interesting.

In [31]:
c = np.random.rand(5,4)
c

array([[0.170336  , 0.69817107, 0.1399532 , 0.30467586],
       [0.14068559, 0.87900447, 0.89560403, 0.23635587],
       [0.51876494, 0.27771471, 0.58562287, 0.35986252],
       [0.54057544, 0.61565758, 0.50739648, 0.71581486],
       [0.47495385, 0.48380363, 0.47921121, 0.73654186]])

In [32]:
c[0,0]

0.17033599958997026

In [33]:
c[:, 0]    # all rows of a single column

array([0.170336  , 0.14068559, 0.51876494, 0.54057544, 0.47495385])

In [34]:
c[:, 1:3]  # all rows of multiple columns

array([[0.69817107, 0.1399532 ],
       [0.87900447, 0.89560403],
       [0.27771471, 0.58562287],
       [0.61565758, 0.50739648],
       [0.48380363, 0.47921121]])

In [35]:
c[-1, :]   # last row, all columns

array([0.47495385, 0.48380363, 0.47921121, 0.73654186])

In [36]:
c[:2, :2]   # sub-array

array([[0.170336  , 0.69817107],
       [0.14068559, 0.87900447]])

You can select these but it is very important to note that all of these are **views** of the original array, NOT copies.  If you assign a new value to the view the original is modified

In [ ]:
b = c[-1, :]
print("Before mod to b, c[-1, :] is: {}".format(c[-1, :]))
print('')
b[:] = 2e3      # NOTE: b = 1e7 assigns the label b to the value 1e7, it does not assign to the array
print("After mods to b, c[-1, :]: {}".format(c[-1, :]))


In [ ]:
# If you don't want a view then copy the data

b = c[-1, :].copy()
print("Before mods to b: {}".format(c[-1, :]))
print('')
b[:] = 3e3    
print("After mods to b: {}".format(c[-1, :]))
b

## Fancy Indexing

In [37]:
c = np.random.randn(10)
c

array([-1.26825503, -1.46910856, -1.32461898, -1.26872483,  0.46259791,
        1.20343066,  1.34451935, -0.29726479, -0.59980132, -1.01332617])

In [38]:
c < 0.0

array([ True,  True,  True,  True, False, False, False,  True,  True,
        True])

In [ ]:
c[c < 0.0]

In [ ]:
# If you want the indexes of the negative values, NOTE: the output is a tuple
lz_idxs = np.nonzero(c < 0.0) 
lz_idxs

In [ ]:
lz_idxs[0]# get the array itself

In [ ]:
# If you just want to count the number of values less than 0, this is by far the fastest way
np.count_nonzero(c < 0.0)

In [ ]:
d=np.random.randn(10000,1000)

In [ ]:
%%timeit
len(np.nonzero(d<0.0)[0])

In [ ]:
%%timeit
np.count_nonzero(d<0.0)

In [ ]:
d=np.random.randn(10,4)
d

In [ ]:
# Select only those rows with negative in the first column
d[d[:, 0] < 0.0, :]

## Operating on arrays

In [39]:
d = np.arange(5)
d

array([0, 1, 2, 3, 4])

In [40]:
e=d*1.23 + 5    # element-wise operation
e

array([5.  , 6.23, 7.46, 8.69, 9.92])

In [41]:
apple =np.array([3.4, 3.24, 1.73, 4.58, 5.67, 3.78, 2.15])

### Member functions

In [42]:
print("Minimum value {} at index {}".format(apple.min(), apple.argmin()))
print("Maximum value {} at index {}".format(apple.max(), apple.argmax()))

Minimum value 1.73 at index 2
Maximum value 5.67 at index 4


In [43]:
# Mean, median, variance and standard deviation

mnv = apple.mean()
vrv = apple.var()
sdv = apple.std()

print("Mean value {:.4f}".format(mnv))
print("Variance {:.4f}, standard deviation {:.4f}".format(vrv, sdv))

Mean value 3.5071
Variance 1.5695, standard deviation 1.2528


### Universal functions

Unviersal functions or `ufuncs` are numpy functions that can be applied to an array or in the case of 2 and higher dimensional arrays along a particular axis.  These functions will return either a value or an array depending on their identity (statistical summary functions reduce the dimensionality) and how they are called.  Here are some statistical examples

In [44]:
minval, minloc = np.amin(apple), np.argmin(apple)
maxval, maxloc = np.amax(apple), np.argmax(apple)

print("Minimum value {} at index {}".format(minval, minloc))
print("Maximum value {} at index {}".format(maxval, maxloc))

Minimum value 1.73 at index 2
Maximum value 5.67 at index 4


In [ ]:
# Peak-to-peak or range of values in array (max-min)
ptpval = np.ptp(apple)  

ptpval == np.amax(apple)-np.amin(apple)   # Compare outputs

In [ ]:
# Mean, median, variance and standard deviation

mnv = np.mean(apple)
mdv = np.median(apple)      # NOTE: apple.median() doesn't exist, why? 
vrv = np.var(apple)
sdv = np.std(apple)

print("Mean value {:.4f}, median value {:.4f}".format(mnv, mdv))
print("Variance {:.4f}, standard deviation {:.4f}".format(vrv, sdv))

In [ ]:
# Apply Bessel's correction to sample varaince and standard deviation
#   divide by N-1 instead of N in formulas
s1 = np.std(apple, ddof=1) 
v1 = np.var(apple, ddof=1)

print("Variance {:.4f}, standard deviation {:.4f}".format(v1, s1))

In [ ]:
# Weighted average also supported
wghts = [1.0, 2.0, 1.0, 1.0, 30.0, 6.0, 1.0]
uwmnv = np.average(apple)
wmnv = np.average(apple, weights=wghts)

print("Unweighted mean value: {:.4f}".format(uwmnv))
print("Weighted mean value:   {:.4f}".format(wmnv))

Additional `ufuncs` are available for

- trigonometric functions `sin`, `cos`, `tan`, `arcsin`, `arccos`, `arctan` 
- hyperbolic functions: `sinh`, `cosh`, `tanh`, ...
- exponential functions: `exp`, `log`, `log10`, ...
- rounding: `round`, `floor`, `ceil`, ...
- summation, products and difference: `sum`, `cumsum`, `cumprod`, `diff`, ...
- statistical functions: as above

and many more.  The majority of these function operate element by element, but much faster than looping through each element can calling a bare Python function.

## Handling nans

In [ ]:
pear = np.array([1.2, 2.3, np.nan, 3.4, 4.6, 7.9,])
pear

In [ ]:
np.amax(pear), np.nanmax(pear)

In [ ]:
np.mean(pear), np.nanmean(pear)

In [ ]:
# Sanity check
(1.2+2.3+3.4+4.6+7.9)/5 == np.nanmean(pear)

## Working with 2D arrays

In [ ]:
peach = np.array([[1, 3], [4, 6], [15, 20]])
peach

In [ ]:
np.amax(peach)

In [ ]:
# axis 0 is the "first axis" or columns (give me the min of each column)
# axis 1 is the "second axis" or rows (give me the min for each row)

np.amin(peach, axis=0), np.amin(peach, axis=1)

In [ ]:
# Statistical functions also work this way
np.mean(peach, axis=0), np.std(peach, axis=0)

## Other features

The primary features that I use day to day are detailed above, there are many additional features:

- [numpy.fft](http://docs.scipy.org/doc/numpy/reference/routines.fft.html): support for FFT evaluation
- [numpy.ma](http://docs.scipy.org/doc/numpy/reference/routines.ma.html): support for creating masked arrays
- [numpy.linalg](http://docs.scipy.org/doc/numpy/reference/routines.linalg.html): support for linear algebra, matrix inversion, eigenvalues, ...
- [numpy.random](http://docs.scipy.org/doc/numpy/reference/routines.random.html): random sampling, statistical distribution functions, ...